package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseContract<M extends BaseContract<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public M setPictureUrl(java.lang.String pictureUrl) {
		set("picture_url", pictureUrl);
		return (M)this;
	}

	public java.lang.String getPictureUrl() {
		return get("picture_url");
	}

	public M setShareDate(java.util.Date shareDate) {
		set("share_date", shareDate);
		return (M)this;
	}

	public java.util.Date getShareDate() {
		return get("share_date");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setCarId(java.lang.Integer carId) {
		set("car_id", carId);
		return (M)this;
	}

	public java.lang.Integer getCarId() {
		return get("car_id");
	}

	public M setReviewId(java.lang.Integer reviewId) {
		set("review_id", reviewId);
		return (M)this;
	}

	public java.lang.Integer getReviewId() {
		return get("review_id");
	}

	public M setBrandId(java.lang.Integer brandId) {
		set("brand_id", brandId);
		return (M)this;
	}

	public java.lang.Integer getBrandId() {
		return get("brand_id");
	}

}
