package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseApply<M extends BaseApply<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setActiveId(java.lang.Integer activeId) {
		set("active_id", activeId);
		return (M)this;
	}

	public java.lang.Integer getActiveId() {
		return get("active_id");
	}

	public M setTime(java.lang.String time) {
		set("time", time);
		return (M)this;
	}

	public java.lang.String getTime() {
		return get("time");
	}

	public M setQq(java.lang.String qq) {
		set("qq", qq);
		return (M)this;
	}

	public java.lang.String getQq() {
		return get("qq");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return get("type");
	}

	public M setAcitiv(java.lang.String acitiv) {
		set("acitiv", acitiv);
		return (M)this;
	}

	public java.lang.String getAcitiv() {
		return get("acitiv");
	}

	public M setStyle(java.lang.String style) {
		set("style", style);
		return (M)this;
	}

	public java.lang.String getStyle() {
		return get("style");
	}

	public M setModel(java.lang.String model) {
		set("model", model);
		return (M)this;
	}

	public java.lang.String getModel() {
		return get("model");
	}

	public M setColor(java.lang.String color) {
		set("color", color);
		return (M)this;
	}

	public java.lang.String getColor() {
		return get("color");
	}

	public M setLowPrice(java.math.BigDecimal lowPrice) {
		set("lowPrice", lowPrice);
		return (M)this;
	}

	public java.math.BigDecimal getLowPrice() {
		return get("lowPrice");
	}

	public M setLickPrice(java.math.BigDecimal lickPrice) {
		set("lickPrice", lickPrice);
		return (M)this;
	}

	public java.math.BigDecimal getLickPrice() {
		return get("lickPrice");
	}

	public M setLoan(java.lang.String loan) {
		set("loan", loan);
		return (M)this;
	}

	public java.lang.String getLoan() {
		return get("loan");
	}

	public M setNum(java.lang.Integer num) {
		set("num", num);
		return (M)this;
	}

	public java.lang.Integer getNum() {
		return get("num");
	}

	public M setLocation(java.lang.String location) {
		set("location", location);
		return (M)this;
	}

	public java.lang.String getLocation() {
		return get("location");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
