package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCarhot<M extends BaseCarhot<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setCarId(java.lang.Integer carId) {
		set("car_id", carId);
		return (M)this;
	}

	public java.lang.Integer getCarId() {
		return get("car_id");
	}

	public M setTime(java.lang.Integer time) {
		set("time", time);
		return (M)this;
	}

	public java.lang.Integer getTime() {
		return get("time");
	}

	public M setTimes(java.lang.Integer times) {
		set("times", times);
		return (M)this;
	}

	public java.lang.Integer getTimes() {
		return get("times");
	}

	public M setBegin(java.lang.String begin) {
		set("begin", begin);
		return (M)this;
	}

	public java.lang.String getBegin() {
		return get("begin");
	}

	public M setEnd(java.lang.String end) {
		set("end", end);
		return (M)this;
	}

	public java.lang.String getEnd() {
		return get("end");
	}

}
