package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInsure<M extends BaseInsure<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setPictureUrl(java.lang.String pictureUrl) {
		set("picture_url", pictureUrl);
		return (M)this;
	}

	public java.lang.String getPictureUrl() {
		return get("picture_url");
	}

	public M setAccessPath(java.lang.String accessPath) {
		set("access_path", accessPath);
		return (M)this;
	}

	public java.lang.String getAccessPath() {
		return get("access_path");
	}

	public M setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
		return (M)this;
	}

	public java.lang.String getIntroduction() {
		return get("introduction");
	}

	public M setDelId(java.lang.Integer delId) {
		set("del_id", delId);
		return (M)this;
	}

	public java.lang.Integer getDelId() {
		return get("del_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setLastUpdateTime(java.util.Date lastUpdateTime) {
		set("last_update_time", lastUpdateTime);
		return (M)this;
	}

	public java.util.Date getLastUpdateTime() {
		return get("last_update_time");
	}

}
