package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShop<M extends BaseShop<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public M setContext(java.lang.String context) {
		set("context", context);
		return (M)this;
	}

	public java.lang.String getContext() {
		return get("context");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setJinkoushui(java.math.BigDecimal jinkoushui) {
		set("jinkoushui", jinkoushui);
		return (M)this;
	}

	public java.math.BigDecimal getJinkoushui() {
		return get("jinkoushui");
	}

	public M setKeyId(java.lang.String keyId) {
		set("key_id", keyId);
		return (M)this;
	}

	public java.lang.String getKeyId() {
		return get("key_id");
	}

	public M setModelId(java.lang.Integer modelId) {
		set("model_id", modelId);
		return (M)this;
	}

	public java.lang.Integer getModelId() {
		return get("model_id");
	}

	public M setDelId(java.lang.Integer delId) {
		set("del_id", delId);
		return (M)this;
	}

	public java.lang.Integer getDelId() {
		return get("del_id");
	}

	public M setAddTime(java.util.Date addTime) {
		set("add_time", addTime);
		return (M)this;
	}

	public java.util.Date getAddTime() {
		return get("add_time");
	}

}
