package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActive<M extends BaseActive<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setStartTime(java.lang.String startTime) {
		set("start_time", startTime);
		return (M)this;
	}

	public java.lang.String getStartTime() {
		return get("start_time");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public M setEndTime(java.lang.String endTime) {
		set("end_time", endTime);
		return (M)this;
	}

	public java.lang.String getEndTime() {
		return get("end_time");
	}

	public M setContext(java.lang.String context) {
		set("context", context);
		return (M)this;
	}

	public java.lang.String getContext() {
		return get("context");
	}

	public M setTimeKeep(java.lang.Integer timeKeep) {
		set("time_keep", timeKeep);
		return (M)this;
	}

	public java.lang.Integer getTimeKeep() {
		return get("time_keep");
	}

	public M setBrandId(java.lang.Integer brandId) {
		set("brand_id", brandId);
		return (M)this;
	}

	public java.lang.Integer getBrandId() {
		return get("brand_id");
	}

	public M setImg(java.lang.String img) {
		set("img", img);
		return (M)this;
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setTime(java.lang.String time) {
		set("time", time);
		return (M)this;
	}

	public java.lang.String getTime() {
		return get("time");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return get("url");
	}

}
