package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseImg<M extends BaseImg<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public M setCarId(java.lang.Integer carId) {
		set("car_id", carId);
		return (M)this;
	}

	public java.lang.Integer getCarId() {
		return get("car_id");
	}

	public M setFlagId(java.lang.Integer flagId) {
		set("flag_id", flagId);
		return (M)this;
	}

	public java.lang.Integer getFlagId() {
		return get("flag_id");
	}

	public M setShopId(java.lang.Integer shopId) {
		set("shop_id", shopId);
		return (M)this;
	}

	public java.lang.Integer getShopId() {
		return get("shop_id");
	}

}
