package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBbs<M extends BaseBbs<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public M setCarId(java.lang.Integer carId) {
		set("car_id", carId);
		return (M)this;
	}

	public java.lang.Integer getCarId() {
		return get("car_id");
	}

	public M setShareDate(java.lang.String shareDate) {
		set("share_date", shareDate);
		return (M)this;
	}

	public java.lang.String getShareDate() {
		return get("share_date");
	}

	public M setComment(java.lang.String comment) {
		set("comment", comment);
		return (M)this;
	}

	public java.lang.String getComment() {
		return get("comment");
	}

	public M setBuyDate(java.lang.String buyDate) {
		set("buy_date", buyDate);
		return (M)this;
	}

	public java.lang.String getBuyDate() {
		return get("buy_date");
	}

	public M setBuyPrice(java.lang.String buyPrice) {
		set("buy_price", buyPrice);
		return (M)this;
	}

	public java.lang.String getBuyPrice() {
		return get("buy_price");
	}

	public M setIsPass(java.lang.Integer isPass) {
		set("isPass", isPass);
		return (M)this;
	}

	public java.lang.Integer getIsPass() {
		return get("isPass");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setZan(java.lang.Integer zan) {
		set("zan", zan);
		return (M)this;
	}

	public java.lang.Integer getZan() {
		return get("zan");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	public java.lang.String getCreateTime() {
		return get("createTime");
	}

}
