package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCar<M extends BaseCar<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setLocationId(java.lang.Integer locationId) {
		set("location_id", locationId);
		return (M)this;
	}

	public java.lang.Integer getLocationId() {
		return get("location_id");
	}

	public M setGuidePrice(java.math.BigDecimal guidePrice) {
		set("guide_price", guidePrice);
		return (M)this;
	}

	public java.math.BigDecimal getGuidePrice() {
		return get("guide_price");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public M setModelsId(java.lang.Integer modelsId) {
		set("models_id", modelsId);
		return (M)this;
	}

	public java.lang.Integer getModelsId() {
		return get("models_id");
	}

	public M setColorId(java.lang.Integer colorId) {
		set("color_id", colorId);
		return (M)this;
	}

	public java.lang.Integer getColorId() {
		return get("color_id");
	}

	public M setBrandId(java.lang.Integer brandId) {
		set("brand_id", brandId);
		return (M)this;
	}

	public java.lang.Integer getBrandId() {
		return get("brand_id");
	}

	public M setPriceId(java.lang.Integer priceId) {
		set("price_id", priceId);
		return (M)this;
	}

	public java.lang.Integer getPriceId() {
		return get("price_id");
	}

	public M setLevelId(java.lang.Integer levelId) {
		set("level_id", levelId);
		return (M)this;
	}

	public java.lang.Integer getLevelId() {
		return get("level_id");
	}

	public M setCid(java.lang.Integer cid) {
		set("cid", cid);
		return (M)this;
	}

	public java.lang.Integer getCid() {
		return get("cid");
	}

	public M setEnergId(java.lang.Integer energId) {
		set("energ_id", energId);
		return (M)this;
	}

	public java.lang.Integer getEnergId() {
		return get("energ_id");
	}

	public M setDisId(java.lang.Integer disId) {
		set("dis_id", disId);
		return (M)this;
	}

	public java.lang.Integer getDisId() {
		return get("dis_id");
	}

	public M setGearboxId(java.lang.Integer gearboxId) {
		set("gearbox_id", gearboxId);
		return (M)this;
	}

	public java.lang.Integer getGearboxId() {
		return get("gearbox_id");
	}

	public M setSeatsId(java.lang.Integer seatsId) {
		set("seats_id", seatsId);
		return (M)this;
	}

	public java.lang.Integer getSeatsId() {
		return get("seats_id");
	}

	public M setDriveId(java.lang.Integer driveId) {
		set("drive_id", driveId);
		return (M)this;
	}

	public java.lang.Integer getDriveId() {
		return get("drive_id");
	}

	public M setYearsId(java.lang.Integer yearsId) {
		set("years_id", yearsId);
		return (M)this;
	}

	public java.lang.Integer getYearsId() {
		return get("years_id");
	}

	public M setDelId(java.lang.Integer delId) {
		set("del_id", delId);
		return (M)this;
	}

	public java.lang.Integer getDelId() {
		return get("del_id");
	}

	public M setLookTimes(java.lang.Integer lookTimes) {
		set("look_times", lookTimes);
		return (M)this;
	}

	public java.lang.Integer getLookTimes() {
		return get("look_times");
	}

	public M setTeamId(java.lang.Integer teamId) {
		set("team_id", teamId);
		return (M)this;
	}

	public java.lang.Integer getTeamId() {
		return get("team_id");
	}

	public M setFadianji(java.lang.String fadianji) {
		set("fadianji", fadianji);
		return (M)this;
	}

	public java.lang.String getFadianji() {
		return get("fadianji");
	}

	public M setHuanbaobiaozhun(java.lang.String huanbaobiaozhun) {
		set("huanbaobiaozhun", huanbaobiaozhun);
		return (M)this;
	}

	public java.lang.String getHuanbaobiaozhun() {
		return get("huanbaobiaozhun");
	}

	public M setRanyou(java.lang.String ranyou) {
		set("ranyou", ranyou);
		return (M)this;
	}

	public java.lang.String getRanyou() {
		return get("ranyou");
	}

	public M setZonghegongkuangyouhao(java.lang.String zonghegongkuangyouhao) {
		set("zonghegongkuangyouhao", zonghegongkuangyouhao);
		return (M)this;
	}

	public java.lang.String getZonghegongkuangyouhao() {
		return get("zonghegongkuangyouhao");
	}

	public M setChemenshu(java.lang.Integer chemenshu) {
		set("chemenshu", chemenshu);
		return (M)this;
	}

	public java.lang.Integer getChemenshu() {
		return get("chemenshu");
	}

	public M setZuoweishu(java.lang.Integer zuoweishu) {
		set("zuoweishu", zuoweishu);
		return (M)this;
	}

	public java.lang.Integer getZuoweishu() {
		return get("zuoweishu");
	}

	public M setCheshenxingshi(java.lang.String cheshenxingshi) {
		set("cheshenxingshi", cheshenxingshi);
		return (M)this;
	}

	public java.lang.String getCheshenxingshi() {
		return get("cheshenxingshi");
	}

	public M setChangkuaigao(java.lang.String changkuaigao) {
		set("changkuaigao", changkuaigao);
		return (M)this;
	}

	public java.lang.String getChangkuaigao() {
		return get("changkuaigao");
	}

	public M setZhouqu(java.lang.Integer zhouqu) {
		set("zhouqu", zhouqu);
		return (M)this;
	}

	public java.lang.Integer getZhouqu() {
		return get("zhouqu");
	}

	public M setZhengtijuli(java.lang.Integer zhengtijuli) {
		set("zhengtijuli", zhengtijuli);
		return (M)this;
	}

	public java.lang.Integer getZhengtijuli() {
		return get("zhengtijuli");
	}

	public M setYouxiangyouji(java.lang.Integer youxiangyouji) {
		set("youxiangyouji", youxiangyouji);
		return (M)this;
	}

	public java.lang.Integer getYouxiangyouji() {
		return get("youxiangyouji");
	}

	public M setXinglixiangrongji(java.lang.Integer xinglixiangrongji) {
		set("xinglixiangrongji", xinglixiangrongji);
		return (M)this;
	}

	public java.lang.Integer getXinglixiangrongji() {
		return get("xinglixiangrongji");
	}

	public M setBaoxiuzhengce(java.lang.String baoxiuzhengce) {
		set("baoxiuzhengce", baoxiuzhengce);
		return (M)this;
	}

	public java.lang.String getBaoxiuzhengce() {
		return get("baoxiuzhengce");
	}

	public M setJinqixingshi(java.lang.String jinqixingshi) {
		set("jinqixingshi", jinqixingshi);
		return (M)this;
	}

	public java.lang.String getJinqixingshi() {
		return get("jinqixingshi");
	}

	public M setZuidamali(java.lang.Integer zuidamali) {
		set("zuidamali", zuidamali);
		return (M)this;
	}

	public java.lang.Integer getZuidamali() {
		return get("zuidamali");
	}

	public M setZuidagonglv(java.lang.Integer zuidagonglv) {
		set("zuidagonglv", zuidagonglv);
		return (M)this;
	}

	public java.lang.Integer getZuidagonglv() {
		return get("zuidagonglv");
	}

	public M setZuidagonglvzhuansu(java.lang.String zuidagonglvzhuansu) {
		set("zuidagonglvzhuansu", zuidagonglvzhuansu);
		return (M)this;
	}

	public java.lang.String getZuidagonglvzhuansu() {
		return get("zuidagonglvzhuansu");
	}

	public M setZuidaniuli(java.lang.Integer zuidaniuli) {
		set("zuidaniuli", zuidaniuli);
		return (M)this;
	}

	public java.lang.Integer getZuidaniuli() {
		return get("zuidaniuli");
	}

	public M setNiujuzhuanshu(java.lang.String niujuzhuanshu) {
		set("niujuzhuanshu", niujuzhuanshu);
		return (M)this;
	}

	public java.lang.String getNiujuzhuanshu() {
		return get("niujuzhuanshu");
	}

	public M setGongyoufangshi(java.lang.String gongyoufangshi) {
		set("gongyoufangshi", gongyoufangshi);
		return (M)this;
	}

	public java.lang.String getGongyoufangshi() {
		return get("gongyoufangshi");
	}

	public M setQudongfangshi(java.lang.String qudongfangshi) {
		set("qudongfangshi", qudongfangshi);
		return (M)this;
	}

	public java.lang.String getQudongfangshi() {
		return get("qudongfangshi");
	}

	public M setZhulileixing(java.lang.String zhulileixing) {
		set("zhulileixing", zhulileixing);
		return (M)this;
	}

	public java.lang.String getZhulileixing() {
		return get("zhulileixing");
	}

	public M setQianxuanguaxingshi(java.lang.String qianxuanguaxingshi) {
		set("qianxuanguaxingshi", qianxuanguaxingshi);
		return (M)this;
	}

	public java.lang.String getQianxuanguaxingshi() {
		return get("qianxuanguaxingshi");
	}

	public M setHouxuanguaxingshi(java.lang.String houxuanguaxingshi) {
		set("houxuanguaxingshi", houxuanguaxingshi);
		return (M)this;
	}

	public java.lang.String getHouxuanguaxingshi() {
		return get("houxuanguaxingshi");
	}

	public M setQianzhidongguige(java.lang.String qianzhidongguige) {
		set("qianzhidongguige", qianzhidongguige);
		return (M)this;
	}

	public java.lang.String getQianzhidongguige() {
		return get("qianzhidongguige");
	}

	public M setHouzhidongguige(java.lang.String houzhidongguige) {
		set("houzhidongguige", houzhidongguige);
		return (M)this;
	}

	public java.lang.String getHouzhidongguige() {
		return get("houzhidongguige");
	}

	public M setShoushaleixing(java.lang.String shoushaleixing) {
		set("shoushaleixing", shoushaleixing);
		return (M)this;
	}

	public java.lang.String getShoushaleixing() {
		return get("shoushaleixing");
	}

	public M setQianluntguige(java.lang.String qianluntguige) {
		set("qianluntguige", qianluntguige);
		return (M)this;
	}

	public java.lang.String getQianluntguige() {
		return get("qianluntguige");
	}

	public M setHouluntguige(java.lang.String houluntguige) {
		set("houluntguige", houluntguige);
		return (M)this;
	}

	public java.lang.String getHouluntguige() {
		return get("houluntguige");
	}

	public M setBiansuxiangxingshi(java.lang.String biansuxiangxingshi) {
		set("biansuxiangxingshi", biansuxiangxingshi);
		return (M)this;
	}

	public java.lang.String getBiansuxiangxingshi() {
		return get("biansuxiangxingshi");
	}

	public M setCarmodelId(java.lang.Integer carmodelId) {
		set("carmodel_id", carmodelId);
		return (M)this;
	}

	public java.lang.Integer getCarmodelId() {
		return get("carmodel_id");
	}

	public M setCountryId(java.lang.Integer countryId) {
		set("country_id", countryId);
		return (M)this;
	}

	public java.lang.Integer getCountryId() {
		return get("country_id");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public M setSetId(java.lang.String setId) {
		set("set_id", setId);
		return (M)this;
	}

	public java.lang.String getSetId() {
		return get("set_id");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.lang.String getUpdateTime() {
		return get("update_time");
	}

	public M setActiveId(java.lang.Integer activeId) {
		set("active_id", activeId);
		return (M)this;
	}

	public java.lang.Integer getActiveId() {
		return get("active_id");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setSeriesId(java.lang.Integer seriesId) {
		set("series_id", seriesId);
		return (M)this;
	}

	public java.lang.Integer getSeriesId() {
		return get("series_id");
	}

	public M setRealPrice(java.math.BigDecimal realPrice) {
		set("real_price", realPrice);
		return (M)this;
	}

	public java.math.BigDecimal getRealPrice() {
		return get("real_price");
	}

	public M setSelPrice(java.math.BigDecimal selPrice) {
		set("sel_price", selPrice);
		return (M)this;
	}

	public java.math.BigDecimal getSelPrice() {
		return get("sel_price");
	}

	public M setSizeId(java.lang.Integer sizeId) {
		set("size_id", sizeId);
		return (M)this;
	}

	public java.lang.Integer getSizeId() {
		return get("size_id");
	}

	public M setTejiache(java.lang.Integer tejiache) {
		set("tejiache", tejiache);
		return (M)this;
	}

	public java.lang.Integer getTejiache() {
		return get("tejiache");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setOther(java.lang.String other) {
		set("other", other);
		return (M)this;
	}

	public java.lang.String getOther() {
		return get("other");
	}

}
