package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseContractImages<M extends BaseContractImages<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setPictureUrl(java.lang.String pictureUrl) {
		set("picture_url", pictureUrl);
		return (M)this;
	}

	public java.lang.String getPictureUrl() {
		return get("picture_url");
	}

	public M setContractId(java.lang.Integer contractId) {
		set("contract_id", contractId);
		return (M)this;
	}

	public java.lang.Integer getContractId() {
		return get("contract_id");
	}

}
