package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseColumn<M extends BaseColumn<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setPid(java.lang.Integer pid) {
		set("pid", pid);
		return (M)this;
	}

	public java.lang.Integer getPid() {
		return get("pid");
	}

	public M setHeadDisplay(java.lang.String headDisplay) {
		set("headDisplay", headDisplay);
		return (M)this;
	}

	public java.lang.String getHeadDisplay() {
		return get("headDisplay");
	}

	public M setAgreement(java.lang.String agreement) {
		set("agreement", agreement);
		return (M)this;
	}

	public java.lang.String getAgreement() {
		return get("agreement");
	}

}
