package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setSubmitTime(java.lang.String submitTime) {
		set("submit_time", submitTime);
		return (M)this;
	}

	public java.lang.String getSubmitTime() {
		return get("submit_time");
	}

	public M setCarId(java.lang.Integer carId) {
		set("car_id", carId);
		return (M)this;
	}

	public java.lang.Integer getCarId() {
		return get("car_id");
	}

	public M setPay(java.lang.Integer pay) {
		set("pay", pay);
		return (M)this;
	}

	public java.lang.Integer getPay() {
		return get("pay");
	}

	public M setDelId(java.lang.Integer delId) {
		set("del_id", delId);
		return (M)this;
	}

	public java.lang.Integer getDelId() {
		return get("del_id");
	}

	public M setColorId(java.lang.Integer colorId) {
		set("color_id", colorId);
		return (M)this;
	}

	public java.lang.Integer getColorId() {
		return get("color_id");
	}

	public M setBuyStyle(java.lang.String buyStyle) {
		set("buy_style", buyStyle);
		return (M)this;
	}

	public java.lang.String getBuyStyle() {
		return get("buy_style");
	}

	public M setBuyTime(java.lang.String buyTime) {
		set("buy_time", buyTime);
		return (M)this;
	}

	public java.lang.String getBuyTime() {
		return get("buy_time");
	}

	public M setGuidance(java.lang.String guidance) {
		set("guidance", guidance);
		return (M)this;
	}

	public java.lang.String getGuidance() {
		return get("guidance");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setCityId(java.lang.Integer cityId) {
		set("city_id", cityId);
		return (M)this;
	}

	public java.lang.Integer getCityId() {
		return get("city_id");
	}

}
