package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseKeymap<M extends BaseKeymap<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setKey(java.lang.String key) {
		set("key", key);
		return (M)this;
	}

	public java.lang.String getKey() {
		return get("key");
	}

	public M setValue(java.lang.String value) {
		set("value", value);
		return (M)this;
	}

	public java.lang.String getValue() {
		return get("value");
	}

	public M setTime(java.lang.String time) {
		set("time", time);
		return (M)this;
	}

	public java.lang.String getTime() {
		return get("time");
	}

	public M setModelId(java.lang.Integer modelId) {
		set("model_id", modelId);
		return (M)this;
	}

	public java.lang.Integer getModelId() {
		return get("model_id");
	}

	public M setDisplay(java.lang.Integer display) {
		set("display", display);
		return (M)this;
	}

	public java.lang.Integer getDisplay() {
		return get("display");
	}

	public M setHot(java.lang.Integer hot) {
		set("hot", hot);
		return (M)this;
	}

	public java.lang.Integer getHot() {
		return get("hot");
	}

}
