package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBrand<M extends BaseBrand<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setImg(java.lang.String img) {
		set("img", img);
		return (M)this;
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setLetter(java.lang.String letter) {
		set("letter", letter);
		return (M)this;
	}

	public java.lang.String getLetter() {
		return get("letter");
	}

	public M setNum(java.lang.Integer num) {
		set("num", num);
		return (M)this;
	}

	public java.lang.Integer getNum() {
		return get("num");
	}

	public M setPid(java.lang.Integer pid) {
		set("pid", pid);
		return (M)this;
	}

	public java.lang.Integer getPid() {
		return get("pid");
	}

	public M setLocationId(java.lang.Integer locationId) {
		set("location_id", locationId);
		return (M)this;
	}

	public java.lang.Integer getLocationId() {
		return get("location_id");
	}

	public M setDisplay(java.lang.Integer display) {
		set("display", display);
		return (M)this;
	}

	public java.lang.Integer getDisplay() {
		return get("display");
	}

}
