package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public M setTime(java.lang.String time) {
		set("time", time);
		return (M)this;
	}

	public java.lang.String getTime() {
		return get("time");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setContext(java.lang.String context) {
		set("context", context);
		return (M)this;
	}

	public java.lang.String getContext() {
		return get("context");
	}

	public M setZan(java.lang.Integer zan) {
		set("zan", zan);
		return (M)this;
	}

	public java.lang.Integer getZan() {
		return get("zan");
	}

	public M setPost(java.lang.String post) {
		set("post", post);
		return (M)this;
	}

	public java.lang.String getPost() {
		return get("post");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public M setCarId(java.lang.Integer carId) {
		set("car_id", carId);
		return (M)this;
	}

	public java.lang.Integer getCarId() {
		return get("car_id");
	}

}
