package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("active", "id", Active.class);
		arp.addMapping("admin", "id", Admin.class);
		arp.addMapping("apply", "id", Apply.class);
		arp.addMapping("bbs", "id", Bbs.class);
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("brand", "id", Brand.class);
		arp.addMapping("car", "id", Car.class);
		arp.addMapping("carhot", "id", Carhot.class);
		arp.addMapping("carmodels", "id", Carmodels.class);
		arp.addMapping("city", "id", City.class);
		arp.addMapping("color", "id", Color.class);
		arp.addMapping("column", "id", Column.class);
		arp.addMapping("contentimg", "id", Contentimg.class);
		arp.addMapping("contract", "id", Contract.class);
		arp.addMapping("contract_images", "id", ContractImages.class);
		arp.addMapping("country", "id", Country.class);
		arp.addMapping("displacement", "id", Displacement.class);
		arp.addMapping("drive", "id", Drive.class);
		arp.addMapping("energy", "id", Energy.class);
		arp.addMapping("gearbox", "id", Gearbox.class);
		arp.addMapping("img", "id", Img.class);
		arp.addMapping("insure", "id", Insure.class);
		arp.addMapping("keymap", "id", Keymap.class);
		arp.addMapping("level", "id", Level.class);
		arp.addMapping("location", "id", Location.class);
		arp.addMapping("model", "id", Model.class);
		arp.addMapping("order", "id", Order.class);
		arp.addMapping("post", "id", Post.class);
		arp.addMapping("price", "id", Price.class);
		arp.addMapping("push", "id", Push.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("seats", "id", Seats.class);
		arp.addMapping("serie", "id", Serie.class);
		arp.addMapping("set", "id", Set.class);
		arp.addMapping("shop", "id", Shop.class);
		arp.addMapping("sizetype", "id", Sizetype.class);
		arp.addMapping("team_img", "id", TeamImg.class);
		arp.addMapping("users", "id", Users.class);
		arp.addMapping("years", "id", Years.class);
	}
}

