package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseActive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Active extends BaseActive<Active> {
	public static final Active dao = new Active().dao();

	public List<Active> find() {
		String sql = "select a.*,(select name from brand where id=a.brand_id) from active a";
		return Active.dao.find(sql);
	}

	public List<Active> find(int brand_id) {
		String sql = "select * from active where brand_id=" + brand_id;
		return Active.dao.find(sql);
	}
}
