package com.demo.common.model;

import com.demo.common.model.base.BaseApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Apply extends BaseApply<Apply> {
	public static final Apply dao = new Apply().dao();
}
