package com.demo.common.model;

import java.util.List;

import com.demo.common.Const;
import com.demo.common.model.base.BaseBbs;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bbs extends BaseBbs<Bbs> {
	public static final Bbs dao = new Bbs().dao();

	public Page<Bbs> find(int pageNumber) {
		String select = "select *";
		String sqlExceptSelect = "from bbs where isPass=0";
		return dao.paginate(pageNumber, Const.pageSize, select, sqlExceptSelect);
	}

	public List<Bbs> findByCarId(int carId) {
		String sql = "select * from bbs where car_id=" + carId;
		return dao.find(sql);
	}

}
