package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseBrand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Brand extends BaseBrand<Brand> {
	public static final Brand dao = new Brand().dao();

	public List<Brand> find() {
		String sql = "select * from brand where display is null order by pid";
		return Brand.dao.find(sql);
	}

	public List<Brand> findLetter() {
		String sql = "select DISTINCT letter,num from brand where display is null";
		return Brand.dao.find(sql);
	}

	public List<Brand> findHot() {
		String sql = "select * from brand where img is not null and display is null limit 0,8";
		return Brand.dao.find(sql);
	}

	public List<Brand> findHotIndex() {
		String sql = "select * from brand where img is not null and display is null limit 0,16";
		return Brand.dao.find(sql);
	}

	public Brand findFirst() {
		String sql = "select * from brand where display is null ORDER BY pid desc limit 0,1";
		return Brand.dao.findFirst(sql);
	}

	public Brand findByPid(int pid) {
		String sql = "select * from brand where display is null and pid=" + pid;
		return Brand.dao.findFirst(sql);
	}
}
