package com.demo.common.model;

import java.math.BigDecimal;
import java.util.List;

import com.demo.common.Const;
import com.demo.common.model.base.BaseCar;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Car extends BaseCar<Car> {
	public static final Car dao = new Car().dao();

	public Page<Car> find(int pageNumber, String sql) {
		String select = "select c.*,(SELECT count(1) count from `order` where car_id=c.id) count,(select name from serie where id=c.series_id) as sname";
		String sqlExceptSelect = "from car c where " + sql;
		return dao.paginate(pageNumber, Const.pageSize, select, sqlExceptSelect);
	}

	public List<Car> find(Admin admin) {
		String sql = "select c.*,(select name from years where id=c.years_id) yname,(select name from brand where id=c.brand_id) bname,(select name from serie where id=c.series_id) sname,(select name from carmodels where id=c.carmodel_id) carname from car c where del_id<>2 and user_id="
				+ admin.getId();
		return Car.dao.find(sql);
	}

	public List<Car> findPrice() {
		String sql = "select c.*,(select name from years where id=c.years_id) yname,(select name from brand where id=c.brand_id) bname,(select name from serie where id=c.series_id) sname,(select name from carmodels where id=c.carmodel_id) carname from car c where del_id<>2 and tejiache=1 limit 0,10";
		return Car.dao.find(sql);
	}

	public List<Car> findByTeamAll() {
		String sql = "select c.*,(select name from brand where id=c.brand_id) bname from car c where del_id<>2 and team_id=1";
		return Car.dao.find(sql);
	}

	public List<Car> find(int location_id, int brand_id, Admin admin) {
		String sql = "select c.*,(select name from years where id=c.years_id) yname,(select name from brand where id=c.brand_id) bname,(select name from serie where id=c.series_id) sname,(select name from carmodels where id=c.carmodel_id) carname from car c where del_id<>2 and c.location_id="
				+ location_id + " and c.brand_id=" + brand_id + " and c.user_id=" + admin.getId();
		return Car.dao.find(sql);
	}

	public List<Car> find(int location_id, Admin admin) {
		String sql = "select c.*,(select name from years where id=c.years_id) yname,(select name from brand where id=c.brand_id) bname,(select name from serie where id=c.series_id) sname,(select name from carmodels where id=c.carmodel_id) carname from car c where del_id<>2 and c.location_id="
				+ location_id + " and c.user_id=" + admin.getId();
		return Car.dao.find(sql);
	}

	public List<Car> find(String name, String time1, String time2, Admin admin) {
		String sql = "select c.*,(select name from brand where id=c.brand_id) bname from car c where del_id<>2 and create_time<='"
				+ time2 + "' and create_time>='" + time1 + "' or name like '" + name + "' and user_id=" + admin.getId();
		return Car.dao.find(sql);
	}

	public Car findCarById(int id) {
		String sql = "select (select url from active where id=c.active_id) activeurl,(select name from active where id=c.active_id) activename,c.*,(select name from years where id=c.years_id) as yname,(select name from carmodels where id=c.carmodel_id) as cname,(select name from serie where id=c.series_id) as sname,(select name from brand where id=c.brand_id) as bname,(select name from gearbox where id=c.gearbox_id) as gname,(select name from displacement where id=c.dis_id) as dname,(SELECT count(1) count from `order` where car_id=c.id) count from car c where del_id<>2 and c.id="
				+ id;
		return dao.findFirst(sql);
	}

	public Car findCarByCid(int id) {
		String sql = "select c.*,(select name from years where id=c.years_id) as yname,(select name from carmodels where id=c.carmodel_id) as cname,(select name from serie where id=c.series_id) as sname,(select name from brand where id=c.brand_id) as bname,(select name from gearbox where id=c.gearbox_id) as gname,(select name from displacement where id=c.dis_id) as dname,(SELECT count(1) count from `order` where car_id=c.id) count from car c where del_id<>2 and c.carmodel_id="
				+ id;
		return dao.findFirst(sql);
	}

	public Page<Car> findBySeries(int pageNumber, String sql, String name) {
		String select = "select c.*,(SELECT count(*) count from `order` where car_id=c.id) count,(select name from serie where id=c.series_id) as sname";
		String sqlExceptSelect = "from car c where " + sql + " group by " + name;
		System.out.println(select + sqlExceptSelect);
		return Car.dao.paginate(pageNumber, Const.pageSize, select, sqlExceptSelect);
	}

	public List<Car> find(int brand_id, int series_id, String name) {
		String sql = "select series_id,cid,brand_id,id,(select name from years where id=years_id) yname,(select name from carmodels where id=carmodel_id) cidname from car where brand_id="
				+ brand_id + " and series_id=" + series_id + " and del_id<>2 group by " + name;
		return Car.dao.find(sql);
	}

	public List<Car> find(int brand_id, int series_id, String name, Admin admin) {
		String sql = "select series_id,cid,brand_id,id,(select name from years where id=years_id) yname,(select name from carmodels where id=carmodel_id) cidname from car where brand_id="
				+ brand_id + " and series_id=" + series_id + " and del_id<>2 and user_id=" + admin.getId()
				+ " group by " + name;
		return Car.dao.find(sql);
	}

	public List<Car> find(int brand_id, int series_id, int years_id, String name) {
		String sql = "select c.series_id,c.cid,c.brand_id,c.id,(select name from displacement where id=c.dis_id) dname,(select name from gearbox where id=c.gearbox_id) gname,(SELECT count(1) count from `order` where car_id=c.id) count,(select name from carmodels where id=c.carmodel_id) as cname,(select name from serie where id=c.series_id) as sname,(select name from years where id=years_id) yname,(select name from carmodels where id=c.carmodel_id) cidname from car c where brand_id="
				+ brand_id + " and series_id=" + series_id + " and years_id=" + years_id + " and del_id<>2 group by "
				+ name;
		return Car.dao.find(sql);
	}

	public List<Car> findPrice(BigDecimal bigDecimal) {
		String sql = "SELECT c.url,c.guide_price,(select count(*) from `order` where car_id=c.id) count,c.id,(select name from brand where id=c.brand_id) bname,(select name from serie where id=c.series_id) sname from car c where c.guide_price = "
				+ bigDecimal;
		return dao.find(sql);
	}

}
