package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseCarhot;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Carhot extends BaseCarhot<Carhot> {
	public static final Carhot dao = new Carhot().dao();

	public List<Carhot> find() {
		String sql = "select (select price from car where id=a.car_id) price,(select guide_price from car where id=a.car_id) gprice,(select name from car where id=a.car_id) name,(select url from car where id=a.car_id) url from carhot a where a.times=1 limit 0,5";
		return dao.find(sql);
	}
}
