package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseCarmodels;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Carmodels extends BaseCarmodels<Carmodels> {
	public static final Carmodels dao = new Carmodels().dao();

	public List<Carmodels> find(int series_id) {
		String sql = "select * from carmodels where series_id=" + series_id + "";
		return Carmodels.dao.find(sql);
	}

	public List<Carmodels> find() {
		String sql = "select * from carmodels";
		return Carmodels.dao.find(sql);
	}
}
