package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class City extends BaseCity<City> {
	public static final City dao = new City().dao();

	public List<City> find() {
		String sql = "select * from city where pid is null";
		return dao.find(sql);
	}

	public List<City> findByPid(int pid) {
		String sql = "select * from city where pid=" + pid;
		return dao.find(sql);
	}
}
