package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseColor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Color extends BaseColor<Color> {
	public static final Color dao = new Color().dao();

	public List<Color> find() {
		String sql = "select * from color";
		return dao.find(sql);
	}
}
