package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseColumn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Column extends BaseColumn<Column> {
	public static final Column dao = new Column().dao();

	public List<Column> findAll() {
		String sql = "select a.*,(select id from post where cid=a.id) postid from `column` a";
		return Column.dao.find(sql);
	}

}
