package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseContentimg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Contentimg extends BaseContentimg<Contentimg> {
	public static final Contentimg dao = new Contentimg().dao();

	public List<Contentimg> find(int id) {
		String sql = "select * from contentimg where car_id=" + id;
		return dao.find(sql);
	}

	public List<Contentimg> find() {
		String sql = "select * from contentimg";
		return dao.find(sql);
	}
}
