package com.demo.common.model;

import com.demo.common.model.base.BaseContractImages;;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContractImages extends BaseContractImages<ContractImages> {
	public static final ContractImages dao = new ContractImages().dao();
}
