package com.demo.common.model;

import com.demo.common.model.base.BaseContractAuthority;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContractAuthority extends BaseContractAuthority<ContractAuthority> {
	public static final ContractAuthority dao = new ContractAuthority().dao();
}
