package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseCountry;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Country extends BaseCountry<Country> {
	public static final Country dao = new Country().dao();

	public List<Country> find() {
		String sql = "select * from country";
		return Country.dao.find(sql);
	}
}
