package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseDisplacement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Displacement extends BaseDisplacement<Displacement> {
	public static final Displacement dao = new Displacement().dao();

	public List<Displacement> find() {
		String sql = "SELECT * from displacement";
		return Displacement.dao.find(sql);
	}
}
