package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseDrive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Drive extends BaseDrive<Drive> {
	public static final Drive dao = new Drive().dao();

	public List<Drive> find() {
		String sql = "select * from drive";
		return Drive.dao.find(sql);
	}
}
