package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseEnergy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Energy extends BaseEnergy<Energy> {
	public static final Energy dao = new Energy().dao();

	public List<Energy> find() {
		String sql = "SELECT * from energy";
		return Energy.dao.find(sql);
	}
}
