package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseInsure;
import com.szcarshop.util.StringUtil;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Insure extends BaseInsure<Insure> {
	public static final Insure dao = new Insure().dao();
	
	public List<Insure> find() {
		String sql = "SELECT * FROM insure where del_id <> 2 ORDER BY last_update_time DESC";
		return Insure.dao.find(sql);
	}
	
	public List<Insure> findByThreePara(String name,String startDate,String endDate) {
		StringBuffer sql = new StringBuffer("SELECT * FROM insure where del_id <> 2");
		if(StringUtil.isNotEmpty(name)){
			sql.append(" and name LIKE '%"+name.trim()+"%'");
		}
		if(StringUtil.isNotEmpty(startDate)){
			sql.append(" and last_update_time >= '"+startDate.trim()+"'");
		}
		if(StringUtil.isNotEmpty(endDate)){
			sql.append(" and last_update_time <= '"+endDate.trim()+"'");
		}
		sql.append(" ORDER BY last_update_time DESC");		
		return Insure.dao.find(sql.toString());
	}
	
}
