package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseKeymap;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Keymap extends BaseKeymap<Keymap> {
	public static final Keymap dao = new Keymap().dao();

	public List<Keymap> find() {
		String sql = "select * from keymap";
		return Keymap.dao.find(sql);
	}

	public List<Keymap> findByModel_id(int id) {
		String sql = "select * from keymap where model_id=" + id;
		return Keymap.dao.find(sql);
	}

	public List<Keymap> findByModel_idDintct(int id) {
		String sql = "select * from keymap where model_id=" + id + " group by name";
		return Keymap.dao.find(sql);
	}

	public List<Keymap> findNameNum(int id, int begin, int end) {
		String sql = "select * from keymap where model_id=" + id + " group by name ORDER BY id limit " + begin + ","
				+ end + "";
		return Keymap.dao.find(sql);
	}
}
