package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseLevel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Level extends BaseLevel<Level> {
	public static final Level dao = new Level().dao();

	public List<Level> find() {
		String sql = "select * from `level`";
		return Level.dao.find(sql);
	}
}
