package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseLocation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Location extends BaseLocation<Location> {
	public static final Location dao = new Location().dao();

	public List<Location> find() {
		String sql = "select * from location";
		return Location.dao.find(sql);
	}
}
