package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Model extends BaseModel<Model> {
	public static final Model dao = new Model().dao();

	public List<Model> find() {
		String sql = "select * from model";
		return Model.dao.find(sql);
	}

	public List<Model> findSubModel(int modelId) {
		String sql = "select t1.*,t2.`name` modelName from keymap t1, model t2 where t1.model_id = t2.id and t1.model_id = "
				+ modelId + " and t1.display != 2 order by t1.id desc";
		return Model.dao.find(sql);
	}

}
