package com.demo.common.model;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import com.demo.common.model.base.BaseOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Order extends BaseOrder<Order> {
	public static final Order dao = new Order().dao();

	public List<Order> find(int user_id) {
		String sql = "select a.*,(select name from car where id=a.car_id) carname,(select url from car where id=a.car_id) carurl,(select (select name from carmodels where id=carmodel_id) name from car where id=a.car_id) carmodelname,(select (select name from color where id=color_id) name from car where id=a.car_id) colorname FROM `order` a where a.del_id <>2  and a.user_id="
				+ user_id + "";
		return dao.find(sql);
	}

	public long findNum(int user_id) {
		String sql = "select count(*) count from `order` where del_id<>2 and user_id=" + user_id;
		return dao.findFirst(sql).getLong("count");
	}

	public long findNumByTime(int user_id) {
		SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
		String sql = "select count(1) as num from `order` where del_id<>2 and user_id=" + user_id
				+ " and date_format(submit_time,'%Y%m%d')=" + sdf.format(new Date());
		System.out.println(sql);
		return dao.findFirst(sql).getLong("num");
	}

	public List<Order> find() {
		String sql = "select o.*,(select nick_name from users where id=o.user_id) nick_name,(select (select name from brand where id=c.brand_id) from car c where c.id=o.car_id) brand_name,(select name from car where id=o.car_id) car_name from `order` o where o.del_id <> 2";
		return Order.dao.find(sql);
	}

	public Order findById(Integer car_id, int user_id) {
		String sql = "select * from `order` where car_id=" + car_id + " and user_id=" + user_id;
		return dao.findFirst(sql);
	}
}
