package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BasePost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Post extends BasePost<Post> {
	public static final Post dao = new Post().dao();

	public List<Post> findAll() {
		String sql = "select a.*,(select name from `column` where id=a.cid) cname from post a";
		return dao.find(sql);
	}

	public Post findByCid(int cid) {
		String sql = "select a.*,(select name from `column` where id=a.cid) cname from post a where cid=" + cid;
		return dao.findFirst(sql);
	}
}
