package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BasePrice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Price extends BasePrice<Price> {
	public static final Price dao = new Price().dao();

	public List<Price> find() {
		String sql = "select * from price";
		return Price.dao.find(sql);
	}
}
