package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BasePush;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Push extends BasePush<Push> {
	public static final Push dao = new Push().dao();

	public List<Push> find() {
		String sql = "select p.car_id id,(select name from car where id=p.car_id) carname,(select name from brand where id=p.brand_id) bname,(SELECT name from serie where id=p.series_id) sname,(select url from car where id=p.car_id) url,(SELECT guide_price from car WHERE id=p.car_id) gprice,(SELECT count(*) count from `order` where car_id=p.car_id) count from push p";
		return dao.find(sql);
	}
}
