package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseSeats;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Seats extends BaseSeats<Seats> {
	public static final Seats dao = new Seats().dao();

	public List<Seats> find() {
		String sql = "select * from seats";
		return Seats.dao.find(sql);
	}
}
