package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Set extends BaseSet<Set> {
	public static final Set dao = new Set().dao();

	public List<Set> find() {
		String sql = "select * from `set`";
		return Set.dao.find(sql);
	}
}
