package com.demo.common.model;

import java.util.List;

import org.beetl.ext.fn.StringUtil;

import com.alibaba.druid.util.StringUtils;
import com.demo.common.Const;
import com.demo.common.model.base.BaseShop;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shop extends BaseShop<Shop> {
	public static final Shop dao = new Shop().dao();

	public Page<Shop> find(String sql, int pageNumber) {
		String select = "select s.*,(select name from model where id=s.model_id) mname";
		String sqlpara = "from shop s where s.del_id<>2 and " + sql
				+ " order by id desc";
		System.out.println(select + sqlpara);
		return Shop.dao.paginate(pageNumber, Const.pageSize, select, sqlpara);
	}

	public List<Shop> find(int modelId) {
		String sql = "";
		if (modelId != 0) {
			sql = "select s.*,(select name from model where id=s.model_id) mname from shop s where s.del_id<>2 and s.model_id = "
					+ modelId + " order by id desc";
		} else {
			sql = "select s.*,(select name from model where id=s.model_id) mname from shop s where s.del_id<>2 order by id desc";
		}
		System.out.println(sql);
		return dao.find(sql);
	}

	public List<Shop> find(String name, String time1, String time2) {
		StringBuffer sql = new StringBuffer();
		sql.append("select * from shop where 1 = 1 ");
		if (!StringUtils.isEmpty(name)) {
			sql.append("and title = '" + name + "'");
		}
		if (!StringUtils.isEmpty(time1)) {
			sql.append("and add_time > '" + time1 + "'");
		}
		if (!StringUtils.isEmpty(time2)) {
			sql.append("and add_time < '" + time2 + "'");
		}
		System.out.println(sql.toString());
		return dao.find(sql.toString());
	}

	public List<Shop> findBusiness(int modelId, String userName) {
		String sql = "";
		if (modelId != 0) {
			sql = "select s.*,(select name from model where id=s.model_id) mname from shop s where s.user_name = '"
					+ userName
					+ "' and s.del_id<>2 and s.model_id = "
					+ modelId + " order by id desc";
		} else {
			sql = "select s.*,(select name from model where id=s.model_id) mname from shop s where s.user_name = '"
					+ userName + "' and s.del_id<>2 order by id desc";
		}
		System.out.println(sql);
		return dao.find(sql);
	}
}
