package com.demo.common.model;

import com.demo.common.model.base.BaseSizetype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sizetype extends BaseSizetype<Sizetype> {
	public static final Sizetype dao = new Sizetype().dao();
}
