package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseTeamImg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TeamImg extends BaseTeamImg<TeamImg> {
	public static final TeamImg dao = new TeamImg().dao();

	public List<TeamImg> find() {
		String sql = "select * from team_img";
		return dao.find(sql);
	}
}
