package com.demo.common.model;

import com.demo.common.model.base.BaseUsers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Users extends BaseUsers<Users> {
	public static final Users dao = new Users().dao();

	public Users find(Users user) {
		String sql = "select * from users where user_name='" + user.getUserName() + "' and user_pass='"
				+ user.getUserPass() + "'";
		return Users.dao.findFirst(sql);
	}

	public boolean findUser_name(String user_name) {
		String sql = "select * from users where user_name='" + user_name + "'";
		if (Users.dao.findFirst(sql) != null) {
			return true;
		} else {
			return false;
		}
	}
}
